def print_hangman(wrong_attempts_num):
    if wrong_attempts_num == 0:
        print('..........')
        print('.')
        print('.')
        print('.')
        print('.')
        print('.     -------')
        print('.      |   | ')
        print('.      |   | ')
        print('--------------')
    elif wrong_attempts_num == 1:
        print('..........')
        print('|')
        print('|')
        print('|')
        print('|')
        print('|')
        print('|     -------')
        print('|      |   | ')
        print('|      |   | ')
        print('--------------')
    elif wrong_attempts_num == 2:
        print('----------')
        print('|')
        print('|')
        print('|')
        print('|')
        print('|')
        print('|     -------')
        print('|      |   | ')
        print('|      |   | ')
        print('--------------')
    elif wrong_attempts_num == 3:
        print('----------')
        print('|        |')
        print('|')
        print('|')
        print('|')
        print('|')
        print('|     -------')
        print('|      |   | ')
        print('|      |   | ')
        print('--------------')
    elif wrong_attempts_num == 4:
        print('----------')
        print('|/       |')
        print('|')
        print('|')
        print('|')
        print('|')
        print('|     -------')
        print('|      |   | ')
        print('|      |   | ')
        print('--------------')
    elif wrong_attempts_num == 5:
        print('----------')
        print('|/       |')
        print('|        @')
        print('|')
        print('|')
        print('|')
        print('|     -------')
        print('|      |   | ')
        print('|      |   | ')
        print('--------------')
    elif wrong_attempts_num == 6:
        print('----------')
        print('|/       |')
        print('|        @')
        print('|        |')
        print('|        |')
        print('|')
        print('|     -------')
        print('|      |   | ')
        print('|      |   | ')
        print('--------------')
    elif wrong_attempts_num == 7:
        print('----------')
        print('|/       |')
        print('|        @')
        print('|       /|')
        print('|        |')
        print('|')
        print('|     -------')
        print('|      |   | ')
        print('|      |   | ')
        print('--------------')
    elif wrong_attempts_num == 8:
        print('----------')
        print('|/       |')
        print('|        @')
        print('|       /|\\')
        print('|        |')
        print('|')
        print('|     -------')
        print('|      |   | ')
        print('|      |   | ')
        print('--------------')
    elif wrong_attempts_num == 9:
        print('----------')
        print('|/       |')
        print('|        @')
        print('|       /|\\')
        print('|        |')
        print('|       /  ')
        print('|     -------')
        print('|      |   | ')
        print('|      |   | ')
        print('--------------')
    elif wrong_attempts_num == 10:
        print('----------')
        print('|/       |')
        print('|        @')
        print('|       /|\\')
        print('|        |')
        print('|       / \\')
        print('|     -------')
        print('|      |   | ')
        print('|      |   | ')
        print('--------------')
    elif wrong_attempts_num == 11:
        print('----------')
        print('|/       |')
        print('|        @  *&*%!!')
        print('|       /|\\')
        print('|        |')
        print('|       / \\')
        print('|')
        print('|')
        print('|   YOU DIED ')
        print('--------------')


if __name__ == '__main__':
    for i in range(12):
        print_hangman(i)
        print()
